# Generated by Django 5.2 on 2025-06-12 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_alter_product_name_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Update')], max_length=12)),
                ('quantity', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('timestap', models.DateTimeField(auto_now_add=True)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='products.orderdetail')),
            ],
        ),
    ]
