# Generated by Django 5.2 on 2025-06-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orderdetailauditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetailauditlog',
            old_name='timestap',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='orderdetailauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], max_length=12),
        ),
    ]
